# 单机模式配置
---
spring:
  profiles: develop
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
logging:
  level:
    org.springframework.web: INFO

# 集群模式配置
---
spring:
  profiles: production

logging:
  level:
    org.springframework.web: INFO

---
spring:
  profiles: s1 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@yiran-base-eureka-server-s2.base.svc.cluster.local:${server.port}/eureka/
---
spring:
  profiles: s2
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@yiran-base-eureka-server-s1.base.svc.cluster.local:${server.port}/eureka/

#---
#spring:
#  profiles: s3
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://admin:admin@yiran-base-eureka-server-s1.base.svc.cluster.local:${server.port}/eureka/, http://admin:admin@yiran-base-eureka-server-s3.base.svc.cluster.local:${server.port}/eureka/
      