spring:
  cloud:
    bus:
      ack:
        destination-service: ${spring.application.name}

server:
  session:
    cookie:
      name: OAUTH2SESSION
      
# 单机模式配置
---
spring:
  profiles: develop

#  redis:
#    host: 192.168.40.161
#    port: 30379

#自定义配置，配置默认登陆地址及权限例外路径等
security:
  oauth2:
    authorization:
      loginurl: /login
      deniedurl: /deny
      matchers: /images/**, /checkcode, /scripts/**, /styles/**
#配置鉴权服务信息
    client:
      client-id: eagleeye
      client-secret: $2a$10$rKja7aRhLDrGL3RrCDS1XefGlfb2spiA.YGfzU1.Ul8si2Ir/Z0G.
      authorized-grant-types: authorization_code, refresh_token, password, client_credentials
      scope: webclient, mobileclient

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

# 使用feign+hystrix断路时必须增加以下配置，否则不会生效
feign:
  hystrix:
    enabled: true
logging:
  level:
    org.springframework.web: INFO

# 集群模式配置
---
spring:
  profiles: production

  redis:
    host: 192.168.40.161
    port: 30379

security:
  oauth2:
    authorization:
      loginurl: /login
      deniedurl: /deny
      matchers: /images/**, /checkcode, /scripts/**, /styles/**
    client:
      client-id: eagleeye
      client-secret: $2a$10$rKja7aRhLDrGL3RrCDS1XefGlfb2spiA.YGfzU1.Ul8si2Ir/Z0G.
      authorized-grant-types: authorization_code, refresh_token, password, client_credentials
      scope: webclient, mobileclient

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@yiran-base-eureka-s1.base.svc.cluster.local:8761/eureka/, http://admin:admin@yiran-base-eureka-s2.base.svc.cluster.local:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true 

# 使用feign+hystrix断路时必须增加以下配置，否则不会生效
feign:
  hystrix:
    enabled: true  
logging:
  level:
    org.springframework.web: INFO    